# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_memory_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Memory_change_form(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("font:16pt;\n"
                                   "font-family:\"Georgia\";\n"
                                   "font-weight: bold;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.memory_name_old = QtWidgets.QLineEdit(self.widget)
        self.memory_name_old.setStyleSheet("background-color: #DCDCDC;\n"
                                           "width: 100%;\n"
                                           "padding: 12px;\n"
                                           "border: 0pч;\n"
                                           "border-radius: 13px;\n"
                                           "box-sizing: border-box;\n"
                                           "font-family:\"Georgia\";")
        self.memory_name_old.setText("")
        self.memory_name_old.setMaxLength(100)
        self.memory_name_old.setObjectName("memory_name_old")
        self.verticalLayout.addWidget(self.memory_name_old)
        self.memory_name = QtWidgets.QLineEdit(self.widget)
        self.memory_name.setStyleSheet("background-color: #DCDCDC;\n"
                                       "width: 100%;\n"
                                       "padding: 12px;\n"
                                       "border: 0pч;\n"
                                       "border-radius: 13px;\n"
                                       "box-sizing: border-box;\n"
                                       "font-family:\"Georgia\";")
        self.memory_name.setText("")
        self.memory_name.setMaxLength(100)
        self.memory_name.setObjectName("memory_name")
        self.verticalLayout.addWidget(self.memory_name)
        self.memory_info = QtWidgets.QPlainTextEdit(self.widget)
        self.memory_info.setStyleSheet("border-radius: 50px;\n"
                                       "margin:5px;\n"
                                       "font-family:\"Georgia\";")
        self.memory_info.setTabChangesFocus(False)
        self.memory_info.setPlainText("")
        self.memory_info.setObjectName("memory_info")
        self.verticalLayout.addWidget(self.memory_info)
        self.change_pic_btn = QtWidgets.QPushButton(self.widget)
        self.change_pic_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.change_pic_btn.setStyleSheet("display: inline-block;\n"
                                          "border-radius: 10px;\n"
                                          "background-color: gray;\n"
                                          "background-position: 100% 0;\n"
                                          "font:12pt;\n"
                                          "font-family: \"Georgia\";\n"
                                          "font-weight: bold;\n"
                                          "color: white;\n"
                                          "box-shadow: 0 16px 32px 0 rgba(0, 40, 120, .35);\n"
                                          "transition: .5s;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_pic_btn.setIcon(icon)
        self.change_pic_btn.setIconSize(QtCore.QSize(20, 20))
        self.change_pic_btn.setObjectName("change_pic_btn")
        self.verticalLayout.addWidget(self.change_pic_btn)
        self.memory_coords = QtWidgets.QLineEdit(self.widget)
        self.memory_coords.setStyleSheet("background-color: #DCDCDC;\n"
                                         "width: 100%;\n"
                                         "padding: 12px;\n"
                                         "border: 0pч;\n"
                                         "border-radius: 13px;\n"
                                         "box-sizing: border-box;\n"
                                         "font-family: \"Georgia\";")
        self.memory_coords.setText("")
        self.memory_coords.setMaxLength(100)
        self.memory_coords.setObjectName("memory_coords")
        self.verticalLayout.addWidget(self.memory_coords)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.change_memory_btn = QtWidgets.QPushButton(self.widget)
        self.change_memory_btn.setMinimumSize(QtCore.QSize(301, 61))
        self.change_memory_btn.setStyleSheet("display: inline-block;\n"
                                             "margin: 10px 0px;\n"
                                             "border-radius: 20px;\n"
                                             "background-color: #4267B2;\n"
                                             "background-position: 100% 0;\n"
                                             "font:19pt;\n"
                                             "font-family:\"Georgia\";\n"
                                             "font-weight: bold;\n"
                                             "color: white;\n"
                                             "box-shadow: 0 16px 32px 0 rgba(0, 40, 120, .35);\n"
                                             "transition: .5s;")
        self.change_memory_btn.setObjectName("change_memory_btn")
        self.gridLayout_2.addWidget(self.change_memory_btn, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Изменение воспоминания"))
        self.label_2.setText(_translate("MainWindow", "Отредактируйте воспоминание"))
        self.memory_name_old.setPlaceholderText(_translate("MainWindow", "Старое название:"))
        self.memory_name.setPlaceholderText(_translate("MainWindow", "Новое название:"))
        self.memory_info.setPlaceholderText(_translate("MainWindow", "Информация:"))
        self.change_pic_btn.setText(_translate("MainWindow", "Заменить фото"))
        self.memory_coords.setPlaceholderText(
            _translate("MainWindow", "Координаты места через пробел (необязательно):"))
        self.change_memory_btn.setText(_translate("MainWindow", "Отредактировать"))
