# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_memory_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Memory_del_form(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 262)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.del_memory_btn = QtWidgets.QPushButton(self.widget)
        self.del_memory_btn.setMinimumSize(QtCore.QSize(301, 61))
        self.del_memory_btn.setStyleSheet("display: inline-block;\n"
                                          "margin: 10px 0px;\n"
                                          "border-radius: 20px;\n"
                                          "background-color: #4267B2;\n"
                                          "background-position: 100% 0;\n"
                                          "font:19pt;\n"
                                          "font-family:\"Georgia\";\n"
                                          "font-weight: bold;\n"
                                          "color: white;\n"
                                          "box-shadow: 0 16px 32px 0 rgba(0, 40, 120, .35);\n"
                                          "transition: .5s;")
        self.del_memory_btn.setObjectName("del_memory_btn")
        self.gridLayout.addWidget(self.del_memory_btn, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("font:19pt;\n"
                                   "font-family:\"Georgia\";\n"
                                   "font-weight: bold;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.memory_name = QtWidgets.QLineEdit(self.widget)
        self.memory_name.setStyleSheet("background-color: #DCDCDC;\n"
                                       "width: 100%;\n"
                                       "padding: 12px;\n"
                                       "border: 0pч;\n"
                                       "border-radius: 13px;\n"
                                       "box-sizing: border-box;\n"
                                       "font-family:\"Georgia\";")
        self.memory_name.setText("")
        self.memory_name.setMaxLength(100)
        self.memory_name.setObjectName("memory_name")
        self.verticalLayout.addWidget(self.memory_name)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Удаление воспоминания"))
        self.del_memory_btn.setText(_translate("MainWindow", "Удалить"))
        self.label_2.setText(_translate("MainWindow", "Удалите воспоминание"))
        self.memory_name.setPlaceholderText(_translate("MainWindow", "Название:"))
