# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'memory_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MemoryForm(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(702, 532)
        MainWindow.setWindowTitle("Воспоминание")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.memory_name = QtWidgets.QLabel(self.widget)
        self.memory_name.setStyleSheet("font:19pt;\n"
                                       "font-family:\"Georgia\";\n"
                                       "font-weight: bold;")
        self.memory_name.setAlignment(QtCore.Qt.AlignCenter)
        self.memory_name.setObjectName("memory_name")
        self.gridLayout.addWidget(self.memory_name, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.memory_info = QtWidgets.QPlainTextEdit(self.widget)
        self.memory_info.setMinimumSize(QtCore.QSize(300, 200))
        self.memory_info.setMaximumSize(QtCore.QSize(700, 600))
        self.memory_info.setStyleSheet("font-family:\"Georgia\";")
        self.memory_info.setTabChangesFocus(False)
        self.memory_info.setReadOnly(True)
        self.memory_info.setPlainText("")
        self.memory_info.setObjectName("memory_info")
        self.horizontalLayout.addWidget(self.memory_info)
        self.image_label = QtWidgets.QLabel(self.widget)
        self.image_label.setMinimumSize(QtCore.QSize(300, 300))
        self.image_label.setStyleSheet("width:70%;")
        self.image_label.setScaledContents(True)
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.horizontalLayout.addWidget(self.image_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.open_map_btn = QtWidgets.QPushButton(self.widget)
        self.open_map_btn.setMinimumSize(QtCore.QSize(301, 61))
        self.open_map_btn.setStyleSheet("display: inline-block;\n"
                                        "margin: 10px 0px;\n"
                                        "border-radius: 20px;\n"
                                        "background-color: #1f4f16;\n"
                                        "background-position: 100% 0;\n"
                                        "font:19pt;\n"
                                        "font-family:\"Georgia\";\n"
                                        "font-weight: bold;\n"
                                        "color: white;\n"
                                        "box-shadow: 0 16px 32px 0 rgba(0, 40, 120, .35);\n"
                                        "transition: .5s;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/map.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_map_btn.setIcon(icon)
        self.open_map_btn.setIconSize(QtCore.QSize(24, 24))
        self.open_map_btn.setObjectName("open_map_btn")
        self.verticalLayout.addWidget(self.open_map_btn)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.close_btn = QtWidgets.QPushButton(self.widget)
        self.close_btn.setMinimumSize(QtCore.QSize(301, 61))
        self.close_btn.setStyleSheet("display: inline-block;\n"
                                     "margin: 10px;\n"
                                     "margin-left:20px;\n"
                                     "margin-right:20px;\n"
                                     "border-radius: 20px;\n"
                                     "background-color: #4267B2;\n"
                                     "background-position: 100% 0;\n"
                                     "font:19pt;\n"
                                     "font-family:\"Georgia\";\n"
                                     "font-weight: bold;\n"
                                     "color: white;\n"
                                     "box-shadow: 0 16px 32px 0 rgba(0, 40, 120, .35);\n"
                                     "transition: .5s;")
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_2.addWidget(self.close_btn)
        self.save_mem_btn = QtWidgets.QPushButton(self.widget)
        self.save_mem_btn.setMaximumSize(QtCore.QSize(70, 150))
        self.save_mem_btn.setStyleSheet("display: inline-block;\n"
                                      "border-radius: 10px;\n"
                                      "background-color: #7cae43;\n"
                                      "background-position: 100% 0;\n"
                                      "font:19pt;\n"
                                      "font-family:\"Georgia\";\n"
                                      "font-weight: bold;\n"
                                      "color: white;\n"
                                      "box-shadow: 0 16px 32px 0 rgba(0, 40, 120, .35);\n"
                                      "transition: .5s;")
        self.save_mem_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/save-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_mem_btn.setIcon(icon1)
        self.save_mem_btn.setIconSize(QtCore.QSize(40, 40))
        self.save_mem_btn.setObjectName("save_mem_btn")
        self.horizontalLayout_2.addWidget(self.save_mem_btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.close_btn.clicked.connect(MainWindow.close)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Воспоминание"))
        self.memory_name.setText(_translate("MainWindow", "ТУТ БУДЕТ НАЗВАНИЕ"))
        self.memory_info.setPlaceholderText(_translate("MainWindow", "Информация:"))
        self.image_label.setText(_translate("MainWindow", "А ТУТ КАРТИНКА"))
        self.open_map_btn.setText(_translate("MainWindow", "Открыть карту места"))
        self.close_btn.setText(_translate("MainWindow", "Закрыть"))
