# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Register_form(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 443)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 120, 301, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Register_lgn = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Register_lgn.setStyleSheet("background-color: #DCDCDC;\n"
                                        "width: 100%;\n"
                                        "padding: 12px;\n"
                                        "border: 0pч;\n"
                                        "border-radius: 13px;\n"
                                        "box-sizing: border-box;\n"
                                        "font-family: \"Georgia\";")
        self.Register_lgn.setText("")
        self.Register_lgn.setMaxLength(20)
        self.Register_lgn.setObjectName("Register_lgn")
        self.verticalLayout.addWidget(self.Register_lgn)
        self.Register_psw = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Register_psw.setStyleSheet("background-color: #DCDCDC;\n"
                                        "width: 100%;\n"
                                        "padding: 12px;\n"
                                        "border: 0pч;\n"
                                        "border-radius: 13px;\n"
                                        "box-sizing: border-box;\n"
                                        "font-family: \"Georgia\";\n"
                                        "letter-spacing: 2px;")
        self.Register_psw.setText("")
        self.Register_psw.setMaxLength(20)
        self.Register_psw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Register_psw.setObjectName("Register_psw")
        self.verticalLayout.addWidget(self.Register_psw)
        self.Register_btn = QtWidgets.QPushButton(self.widget)
        self.Register_btn.setGeometry(QtCore.QRect(50, 310, 301, 61))
        self.Register_btn.setStyleSheet("display: inline-block;\n"
                                        "margin: 10px 0px;\n"
                                        "border-radius: 20px;\n"
                                        "background-color: #4267B2;\n"
                                        "background-position: 100% 0;\n"
                                        "font:19pt;\n"
                                        "font-family: \"Georgia\";\n"
                                        "font-weight: bold;\n"
                                        "color: white;\n"
                                        "box-shadow: 0 16px 32px 0 rgba(0, 40, 120, .35);\n"
                                        "transition: .5s;")
        self.Register_btn.setObjectName("Register_btn")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(-10, 40, 421, 51))
        self.label_2.setStyleSheet("font:19pt;\n"
                                   "font-family: \"Georgia\";\n"
                                   "font-weight: bold;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Регистрация"))
        self.Register_lgn.setPlaceholderText(_translate("MainWindow", "Login:"))
        self.Register_psw.setPlaceholderText(_translate("MainWindow", "Password:"))
        self.Register_btn.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.label_2.setText(_translate("MainWindow", "Зарегистрируйтесь"))
